[tool.poetry]
name = "08"
version = "0.1.0"
description = ""
authors = ["pietr <pietromongiello@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
chainlit = "^2.11.1"
openai = "^2.37.0"
chromadb = "^1.5.9"
ollama = "^0.6.2"
langchain-openai = "^1.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
